version: '3.1'

services:
  vktb-bot:
    depends_on:
      - vktb-db
    build:
      context: .
    environment:
      BOT_NAME: ${BOT_NAME}
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_DB_USERNAME: ${BOT_DB_USERNAME}
      BOT_DB_PASSWORD: ${BOT_DB_PASSWORD}
    restart: always
  vktb-db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: ${BOT_DB_USERNAME}
      MYSQL_PASSWORD: ${BOT_DB_PASSWORD}
      MYSQL_DATABASE: 'vktb_db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '33061:3306'
    expose:
      - '3306'